name: Docs lint
on:
  push:
    paths: ["**/*.md"]
  pull_request:
    paths: ["**/*.md"]
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Success
        run: echo "Lint placeholder"
